---
pool: 'default'
trigger:
  branches:
    include:
      - main
stages:
  - stage: build
    jobs:
     - job: jobbuild
       steps:
        - task: maven@4
          inputs:
            mavenPOMFile: 'pom.xml' 
            publishJUnitResults: true
            testResultFiles: '**/TEST-*.xml' 
            jdkVersionOption: '1.17'
            goals: 'validate'