---
pool: 'default'
trigger:
  branches:
    include:
      - main
stages:
  - stage: build
    jobs:
     - job: jobbuild
       steps:
        - task: maven@3
          inputs:
            mavemPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultFiles: '**/TEST-*.xml' 
            jdkVersionOption: '21'
            goals: 'package'