apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: spring-petclinic-plain
  labels:
    app: spring-petclinic-plain
spec:
  type: LoadBalancer
  ports:
    - port: 9093
      name: http
  selector:
    app: spring-petclinic-plain
