apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: spring-petclinic-plain
  labels:
    app: spring-petclinic-plain
spec:
  type: LoadBalancer
  ports:
    - port: 9094
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: spring-petclinic-plain
